/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package core.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import core.model.CoreExample;
import core.model.CoreExampleModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CoreExample service. Represents a row in the &quot;example_CoreExample&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CoreExampleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CoreExampleImpl}.
 * </p>
 *
 * @author binhth
 * @see CoreExampleImpl
 * @see CoreExample
 * @see CoreExampleModel
 * @generated
 */
@ProviderType
public class CoreExampleModelImpl extends BaseModelImpl<CoreExample>
	implements CoreExampleModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a core example model instance should use the {@link CoreExample} interface instead.
	 */
	public static final String TABLE_NAME = "example_CoreExample";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "coreName", Types.VARCHAR },
			{ "coreType", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("coreName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("coreType", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table example_CoreExample (id_ LONG not null primary key,coreName VARCHAR(75) null,coreType INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table example_CoreExample";
	public static final String ORDER_BY_JPQL = " ORDER BY coreExample.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY example_CoreExample.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(core.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.core.model.CoreExample"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(core.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.core.model.CoreExample"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(core.service.util.ServiceProps.get(
				"lock.expiration.time.core.model.CoreExample"));

	public CoreExampleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CoreExample.class;
	}

	@Override
	public String getModelClassName() {
		return CoreExample.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("coreName", getCoreName());
		attributes.put("coreType", getCoreType());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String coreName = (String)attributes.get("coreName");

		if (coreName != null) {
			setCoreName(coreName);
		}

		Integer coreType = (Integer)attributes.get("coreType");

		if (coreType != null) {
			setCoreType(coreType);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getCoreName() {
		if (_coreName == null) {
			return StringPool.BLANK;
		}
		else {
			return _coreName;
		}
	}

	@Override
	public void setCoreName(String coreName) {
		_coreName = coreName;
	}

	@Override
	public int getCoreType() {
		return _coreType;
	}

	@Override
	public void setCoreType(int coreType) {
		_coreType = coreType;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CoreExample.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CoreExample toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CoreExample)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CoreExampleImpl coreExampleImpl = new CoreExampleImpl();

		coreExampleImpl.setId(getId());
		coreExampleImpl.setCoreName(getCoreName());
		coreExampleImpl.setCoreType(getCoreType());

		coreExampleImpl.resetOriginalValues();

		return coreExampleImpl;
	}

	@Override
	public int compareTo(CoreExample coreExample) {
		long primaryKey = coreExample.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CoreExample)) {
			return false;
		}

		CoreExample coreExample = (CoreExample)obj;

		long primaryKey = coreExample.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CoreExample> toCacheModel() {
		CoreExampleCacheModel coreExampleCacheModel = new CoreExampleCacheModel();

		coreExampleCacheModel.id = getId();

		coreExampleCacheModel.coreName = getCoreName();

		String coreName = coreExampleCacheModel.coreName;

		if ((coreName != null) && (coreName.length() == 0)) {
			coreExampleCacheModel.coreName = null;
		}

		coreExampleCacheModel.coreType = getCoreType();

		return coreExampleCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", coreName=");
		sb.append(getCoreName());
		sb.append(", coreType=");
		sb.append(getCoreType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("core.model.CoreExample");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coreName</column-name><column-value><![CDATA[");
		sb.append(getCoreName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coreType</column-name><column-value><![CDATA[");
		sb.append(getCoreType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CoreExample.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CoreExample.class
		};
	private long _id;
	private String _coreName;
	private int _coreType;
	private CoreExample _escapedModel;
}