/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CoreExample service. Represents a row in the &quot;example_CoreExample&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link core.model.impl.CoreExampleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link core.model.impl.CoreExampleImpl}.
 * </p>
 *
 * @author binhth
 * @see CoreExample
 * @see core.model.impl.CoreExampleImpl
 * @see core.model.impl.CoreExampleModelImpl
 * @generated
 */
@ProviderType
public interface CoreExampleModel extends BaseModel<CoreExample> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a core example model instance should use the {@link CoreExample} interface instead.
	 */

	/**
	 * Returns the primary key of this core example.
	 *
	 * @return the primary key of this core example
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this core example.
	 *
	 * @param primaryKey the primary key of this core example
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this core example.
	 *
	 * @return the ID of this core example
	 */
	public long getId();

	/**
	 * Sets the ID of this core example.
	 *
	 * @param id the ID of this core example
	 */
	public void setId(long id);

	/**
	 * Returns the core name of this core example.
	 *
	 * @return the core name of this core example
	 */
	@AutoEscape
	public String getCoreName();

	/**
	 * Sets the core name of this core example.
	 *
	 * @param coreName the core name of this core example
	 */
	public void setCoreName(String coreName);

	/**
	 * Returns the core type of this core example.
	 *
	 * @return the core type of this core example
	 */
	public int getCoreType();

	/**
	 * Sets the core type of this core example.
	 *
	 * @param coreType the core type of this core example
	 */
	public void setCoreType(int coreType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(core.model.CoreExample coreExample);

	@Override
	public int hashCode();

	@Override
	public CacheModel<core.model.CoreExample> toCacheModel();

	@Override
	public core.model.CoreExample toEscapedModel();

	@Override
	public core.model.CoreExample toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}